<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../launcher/LanguageSettings.cs" Link="LanguageSettings.cs"/><Compile Include="../launcher/Locale.cs" Link="Locale.cs"/></ItemGroup></Project>
