<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net472</TargetFramework><LangVersion>latest</LangVersion><Version>0.1.3</Version><AssemblyName>Local.EuropeCampaignFixes</AssemblyName><SteamAppsRoot Condition="'$(SteamAppsRoot)' == ''">C:/Program Files (x86)/Steam/steamapps</SteamAppsRoot><BannerlordRoot Condition="'$(BannerlordRoot)' == ''">$(SteamAppsRoot)/common/Mount &amp; Blade II Bannerlord</BannerlordRoot><WorkshopContentRoot>$(SteamAppsRoot)/workshop/content/261550</WorkshopContentRoot><GameBin>$(BannerlordRoot)/bin/Win64_Shipping_Client</GameBin></PropertyGroup>
 <ItemGroup>
  <Reference Include="GameInterface"><HintPath>$(WorkshopContentRoot)/3770450698/bin/Win64_Shipping_Client/GameInterface.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="Common"><HintPath>$(WorkshopContentRoot)/3770450698/bin/Win64_Shipping_Client/Common.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.Engine"><HintPath>$(GameBin)/TaleWorlds.Engine.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.DotNet"><HintPath>$(GameBin)/TaleWorlds.DotNet.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="0Harmony"><HintPath>$(WorkshopContentRoot)/2859188632/bin/Win64_Shipping_Client/0Harmony.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.MountAndBlade"><HintPath>$(GameBin)/TaleWorlds.MountAndBlade.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.CampaignSystem"><HintPath>$(GameBin)/TaleWorlds.CampaignSystem.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.Core"><HintPath>$(GameBin)/TaleWorlds.Core.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.Library"><HintPath>$(GameBin)/TaleWorlds.Library.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.ObjectSystem"><HintPath>$(GameBin)/TaleWorlds.ObjectSystem.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.Localization"><HintPath>$(GameBin)/TaleWorlds.Localization.dll</HintPath><Private>false</Private></Reference>
  <Reference Include="TaleWorlds.ScreenSystem"><HintPath>$(GameBin)/TaleWorlds.ScreenSystem.dll</HintPath><Private>false</Private></Reference>
 </ItemGroup>
</Project>
